server:
  port: 8081
spring:
  application:
    name: lieying
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/lieying?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates
    mode: HTML5
    encoding: UTF-8
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/
  devtools:
    restart:
      enabled: true
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 1765770246@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: rmhrktkygivrchdd
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.lieying.bean
logging:
  level:
    org:
      lieying:
          dao: debug

